### ISSUE TITLE
About Uninstalling

### ISSUE THREAD

**Issue by mozgbrasil** [mageplaza/magento-2-webhook#3]
Hi, good morning my friends.

About Uninstalling

I am testing your module and uninstalled by Composer and now the error is being displayed as text, can you help me ?

	1 exception(s):
	Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/mageplaza/module-core/etc/module.xml" file can't be read. Warning!file_get_contents(/shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/mageplaza/module-core/etc/module.xml): failed to open stream: No such file or directory

	Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/mageplaza/module-core/etc/module.xml" file can't be read. Warning!file_get_contents(/shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/mageplaza/module-core/etc/module.xml): failed to open stream: No such file or directory
	#0 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Module/ModuleList/Loader.php(120): Magento\Framework\Filesystem\Driver\File->fileGetContents('/shared/httpd/l...')
	#1 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Module/ModuleList/Loader.php(81): Magento\Framework\Module\ModuleList\Loader->getModuleConfigs()
	#2 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Module/ModuleList.php(72): Magento\Framework\Module\ModuleList\Loader->load()
	#3 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Module/ModuleList.php(92): Magento\Framework\Module\ModuleList->getAll()
	#4 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Module/DbVersionInfo.php(144): Magento\Framework\Module\ModuleList->getOne('Magento_Store')
	#5 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Module/DbVersionInfo.php(59): Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual('Magento_Store', false)
	#6 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Module/DbVersionInfo.php(103): Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate('Magento_Store')
	#7 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(119): Magento\Framework\Module\DbVersionInfo->getDbVersionErrors()
	#8 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(53): Magento\Framework\Module\Plugin\DbStatusValidator->getGroupedDbVersionErrors()
	#9 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\Module\Plugin\DbStatusValidator->beforeDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Magento\Framework\App\Request\Http))
	#10 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
	#11 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
	#12 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
	#13 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
	#14 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
	#15 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
	#16 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
	#17 /shared/httpd/localhost/htdocs/magento/magento-2.3.0-dev02/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
	#18 {main}

**Comment by mozgbrasil** [comment]
Sorry, because it was some kind of cache, I simply rebooted the system and it worked as expected
